SET IDENTITY_INSERT [dbo].[Aturan] ON
INSERT INTO [dbo].[Aturan] ([rule_id], [profesi_id], [o1_algoritma_dan_logika], [o2_desain_relasional], [o3_arsitektur_dan_keamanan], [o4_analisis_kebutuhan_pengguna], [o5_adaptif_dan_inovatif], [Keterangan]) VALUES (1, 1, 1, 0, 0, 0, 1, N'Anda unggul dalam algoritma dan pemikiran logis serta fokus pada pengembangan kode tanpa banyak analisis sistem.')
INSERT INTO [dbo].[Aturan] ([rule_id], [profesi_id], [o1_algoritma_dan_logika], [o2_desain_relasional], [o3_arsitektur_dan_keamanan], [o4_analisis_kebutuhan_pengguna], [o5_adaptif_dan_inovatif], [Keterangan]) VALUES (2, 1, 1, 0, 1, 0, 0, N'Anda menekankan efisiensi dan keamanan kode sebagai programmer teknikal yang matang dan berpengalaman.')
INSERT INTO [dbo].[Aturan] ([rule_id], [profesi_id], [o1_algoritma_dan_logika], [o2_desain_relasional], [o3_arsitektur_dan_keamanan], [o4_analisis_kebutuhan_pengguna], [o5_adaptif_dan_inovatif], [Keterangan]) VALUES (3, 1, 1, 1, 0, 0, 1, N'Anda menguasai logika pemrograman dan struktur data dengan kemampuan teknis yang kuat.')
INSERT INTO [dbo].[Aturan] ([rule_id], [profesi_id], [o1_algoritma_dan_logika], [o2_desain_relasional], [o3_arsitektur_dan_keamanan], [o4_analisis_kebutuhan_pengguna], [o5_adaptif_dan_inovatif], [Keterangan]) VALUES (4, 2, 0, 1, 1, 0, 0, N'Anda fokus menjaga keamanan dan integritas database tanpa banyak terlibat dalam pemrograman aplikasi.')
INSERT INTO [dbo].[Aturan] ([rule_id], [profesi_id], [o1_algoritma_dan_logika], [o2_desain_relasional], [o3_arsitektur_dan_keamanan], [o4_analisis_kebutuhan_pengguna], [o5_adaptif_dan_inovatif], [Keterangan]) VALUES (5, 2, 0, 1, 1, 0, 1, N'Anda adalah administrator database modern yang adaptif terhadap perkembangan teknologi dan kebutuhan data.')
INSERT INTO [dbo].[Aturan] ([rule_id], [profesi_id], [o1_algoritma_dan_logika], [o2_desain_relasional], [o3_arsitektur_dan_keamanan], [o4_analisis_kebutuhan_pengguna], [o5_adaptif_dan_inovatif], [Keterangan]) VALUES (6, 2, 0, 1, 0, 1, 0, N'Anda menghubungkan kebutuhan pengguna dengan desain database yang efisien dan konsisten.')
INSERT INTO [dbo].[Aturan] ([rule_id], [profesi_id], [o1_algoritma_dan_logika], [o2_desain_relasional], [o3_arsitektur_dan_keamanan], [o4_analisis_kebutuhan_pengguna], [o5_adaptif_dan_inovatif], [Keterangan]) VALUES (7, 3, 1, 0, 1, 1, 1, N'Anda adalah developer yang analitis, adaptif, dan mampu merancang solusi dari sisi teknis dan kebutuhan pengguna.')
INSERT INTO [dbo].[Aturan] ([rule_id], [profesi_id], [o1_algoritma_dan_logika], [o2_desain_relasional], [o3_arsitektur_dan_keamanan], [o4_analisis_kebutuhan_pengguna], [o5_adaptif_dan_inovatif], [Keterangan]) VALUES (8, 3, 1, 0, 1, 0, 1, N'Anda berfokus pada arsitektur sistem dan mampu beradaptasi dengan teknologi baru secara cepat.')
INSERT INTO [dbo].[Aturan] ([rule_id], [profesi_id], [o1_algoritma_dan_logika], [o2_desain_relasional], [o3_arsitektur_dan_keamanan], [o4_analisis_kebutuhan_pengguna], [o5_adaptif_dan_inovatif], [Keterangan]) VALUES (9, 4, 0, 1, 0, 1, 1, N'Anda mampu memahami kebutuhan pengguna dan merancang solusi inovatif yang sesuai dengan tujuan organisasi.')
INSERT INTO [dbo].[Aturan] ([rule_id], [profesi_id], [o1_algoritma_dan_logika], [o2_desain_relasional], [o3_arsitektur_dan_keamanan], [o4_analisis_kebutuhan_pengguna], [o5_adaptif_dan_inovatif], [Keterangan]) VALUES (10, 4, 0, 0, 0, 1, 1, N'Anda memiliki kemampuan analisis tinggi untuk memahami kebutuhan pengguna tanpa terlibat langsung dalam pemrograman.')
INSERT INTO [dbo].[Aturan] ([rule_id], [profesi_id], [o1_algoritma_dan_logika], [o2_desain_relasional], [o3_arsitektur_dan_keamanan], [o4_analisis_kebutuhan_pengguna], [o5_adaptif_dan_inovatif], [Keterangan]) VALUES (11, 5, 0, 0, 0, 0, 0, N'Profil Anda menunjukkan kecenderungan yang seimbang sehingga sistem belum dapat menentukan profesi yang paling sesuai.')
SET IDENTITY_INSERT [dbo].[Aturan] OFF